### ISSUE TITLE
Unable to retrieve Rainbow Drop

### ISSUE THREAD

**Issue by grop** [gameboy9/DW3Randomizer#6] opened 2017-03-03 21:02 UTC
I have the Stone of Sunlight, the Staff of Rain and the Sacred Amulet and I'm unable to retrieve the Rainbow Drop.  The Sacred Amulet seems to be equippable which I think is somehow related to not being able to proceed.  

The seed I am using is 9831460.

**Comment by gameboy9** [comment] 2017-03-06 14:27
I have a feeling that this is on all seeds... and I think it's because not only is the Rainbow Drop guy looking for those three items, he's also looking for a trigger.  I may have to change the searchable items to Staff Of Rain, Stones Of Sunlight, and Fairy Flute, and you would therefore be forced to climb the Kol Tower to get the Sacred Amulet.

**Comment by grop** [comment] 2017-03-06 15:45
I have another seed I was able to acquire the Rainbow Drop in, but strangely enough I don't think I even had the Sacred Amulet in inventory.  This seed was 257860111.  I wasn't able to complete the game since I never found the Sphere of Light (irrelevant to this bug), so I had started the 9831460 seed to try again.

**Comment by AllenSeitz** [comment] 2017-04-19 12:23
I just got this in the most recent version. Seed/flags: 617988268_0ay@z

**Comment by gameboy9** [comment] 2017-04-19 12:26
I've been wondering how to set this up... I'll take a look.  Thanks!  :)

**Comment by gameboy9** [comment] 2017-04-30 22:57
Awww crap... I need another seed because the new magic algorithm on this version has scrambled up the randomization, so the seed and flags given won't reproduce the issue.  :(

(or if you can attach to me a ROM that would work too...)

**Comment by gameboy9** [comment] 2017-06-05 01:59
I FINALLY figured it out!  It should be fixed with release 1.1, so I'm closing this issue.

**Closed as completed by gameboy9** 2017-06-05 01:59 UTC
Labels: bug
